config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
      :authorized_applications
  end
  resources :google_results
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'google_results#index'
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }, controllers: {sessions: "users/sessions"}

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  scope '/api' do
    scope '/v1' do
      scope '/google_search' do
        post '/' => 'api/v1/google_search#search'
        get 'report/:id' => 'api/v1/google_search#report'
      end
    end
  end

  get 'template_csv' => 'users#template_csv'
end

app/models/google_result.rb
class GoogleResult < ApplicationRecord
  belongs_to :upload_history

  scope :by_upload, -> (upload_id) { where(upload_history_id: upload_id) }
end

app/controllers/google_results_controller.rb
class GoogleResultsController < ApplicationController
  before_action :set_google_result, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /google_results
  # GET /google_results.json
  def index
    @google_results = GoogleResult.by_upload(params[:id])
    @upload_histories = [['Choose a report', -1]] + UploadHistory.all.pluck(:created_at, :id)
  end

  # GET /google_results/1
  # GET /google_results/1.json
  def show
  end

  # GET /google_results/new
  def new
    @google_result = GoogleResult.new
  end

  # GET /google_results/1/edit
  def edit
  end

  # POST /google_results
  # POST /google_results.json
  def create
    @google_result = GoogleResult.new(google_result_params)

    respond_to do |format|
      if @google_result.save
        format.html { redirect_to @google_result, notice: 'Google result was successfully created.' }
        format.json { render :show, status: :created, location: @google_result }
      else
        format.html { render :new }
        format.json { render json: @google_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /google_results/1
  # PATCH/PUT /google_results/1.json
  def update
    respond_to do |format|
      if @google_result.update(google_result_params)
        format.html { redirect_to @google_result, notice: 'Google result was successfully updated.' }
        format.json { render :show, status: :ok, location: @google_result }
      else
        format.html { render :edit }
        format.json { render json: @google_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /google_results/1
  # DELETE /google_results/1.json
  def destroy
    @google_result.destroy
    respond_to do |format|
      format.html { redirect_to google_results_url, notice: 'Google result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_google_result
      @google_result = GoogleResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def google_result_params
      params.require(:google_result).permit(:keyword, :top_ads_count, :bottom_ads_count, :total_ads_count, :top_ads_urls, :bottom_ads_urls, :non_ads_urls, :links_count, :results_count, :results_search_time, :html_cache)
    end
end

app/helpers/google_results_helper.rb
module GoogleResultsHelper
end

app/views/google_results/_form.html.erb
<%= form_for(google_result) do |f| %>
  <% if google_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(google_result.errors.count, "error") %> prohibited this google_result from being saved:</h2>

      <ul>
      <% google_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keyword %>
    <%= f.text_field :keyword %>
  </div>

  <div class="field">
    <%= f.label :top_ads_count %>
    <%= f.text_field :top_ads_count %>
  </div>

  <div class="field">
    <%= f.label :bottom_ads_count %>
    <%= f.text_field :bottom_ads_count %>
  </div>

  <div class="field">
    <%= f.label :total_ads_count %>
    <%= f.text_field :total_ads_count %>
  </div>

  <div class="field">
    <%= f.label :top_ads_urls %>
    <%= f.text_field :top_ads_urls %>
  </div>

  <div class="field">
    <%= f.label :bottom_ads_urls %>
    <%= f.text_field :bottom_ads_urls %>
  </div>

  <div class="field">
    <%= f.label :non_ads_urls %>
    <%= f.text_field :non_ads_urls %>
  </div>

  <div class="field">
    <%= f.label :links_count %>
    <%= f.text_field :links_count %>
  </div>

  <div class="field">
    <%= f.label :results_count %>
    <%= f.number_field :results_count %>
  </div>

  <div class="field">
    <%= f.label :results_search_time %>
    <%= f.text_field :results_search_time %>
  </div>

  <div class="field">
    <%= f.label :html_cache %>
    <%= f.text_area :html_cache %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/google_results/edit.html.erb
<h1>Editing Google Result</h1>

<%= render 'form', google_result: @google_result %>

<%= link_to 'Show', @google_result %> |
<%= link_to 'Back', google_results_path %>

app/views/google_results/index.html.erb
<%= stylesheet_link_tag 'google_results' %>

<h1>Google Results</h1>
<div class="pull-left">
  <a class="btn btn-info" href="/template_csv">Download template</a>
  <label class="btn btn-primary btn-file">
    Upload keywords csv <input id="keywords_csv" name="keywords_csv[]" type="file" multiple hidden />
  </label>
</div>

<div class="form-inline">
  <div class="col-md-4">
    Report <%= select_tag(:upload_histories, options_for_select(@upload_histories), class: 'form-control') %>
  </div>
</div>

<div class="report">
  <script type="text/template" id="report">
    <%= render 'report' %>
  </script>
</div>

<div class="overlay"></div>

app/views/google_results/new.html.erb
<h1>New Google Result</h1>

<%= render 'form', google_result: @google_result %>

<%= link_to 'Back', google_results_path %>

app/views/google_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @google_result.keyword %>
</p>

<p>
  <strong>Top ads count:</strong>
  <%= @google_result.top_ads_count %>
</p>

<p>
  <strong>Bottom ads count:</strong>
  <%= @google_result.bottom_ads_count %>
</p>

<p>
  <strong>Total ads count:</strong>
  <%= @google_result.total_ads_count %>
</p>

<p>
  <strong>Top ads urls:</strong>
  <%= @google_result.top_ads_urls %>
</p>

<p>
  <strong>Bottom ads urls:</strong>
  <%= @google_result.bottom_ads_urls %>
</p>

<p>
  <strong>Non ads urls:</strong>
  <%= @google_result.non_ads_urls %>
</p>

<p>
  <strong>Links count:</strong>
  <%= @google_result.links_count %>
</p>

<p>
  <strong>Results count:</strong>
  <%= @google_result.results_count %>
</p>

<p>
  <strong>Results search time:</strong>
  <%= @google_result.results_search_time %>
</p>

<p>
  <strong>Html cache:</strong>
  <%= @google_result.html_cache.force_encoding("UTF-8") %>
</p>

<%= link_to 'Edit', edit_google_result_path(@google_result) %> |
<%= link_to 'Back', google_results_path %>